### ISSUE TITLE
v1.1.1 shows HTML in widget

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/tempus-fugit#19]
In version 1.1.1 I get HTML in the list of links. See the screenshot. 
<img width="384" alt="Screenshot-Digging the Digital - Vol Blogdrift!-20231004112714@2x" src="https://github.com/dshanske/tempus-fugit/assets/1940855/b31e98b5-d83f-4b8f-a7fb-4d05a228e5be">

It looks like it renders as normal text instead of HTML? 

![Screenshot-DevTools - diggingthedigital com-20231004113537@2x](https://github.com/dshanske/tempus-fugit/assets/1940855/8c4ada77-fb98-4e91-8b82-5b7781f882c8)

When I deactivate all plugins and just use Tempus Fugit, I get a critical error in my widgets screen. See below.
<img width="932" alt="Screenshot-WordPress › Error-20231004113848@2x" src="https://github.com/dshanske/tempus-fugit/assets/1940855/a46fb080-9765-4a56-b7b2-5c71ab6cd008">

I use WordPress 6.3.1 with the Genesis theme. Any help is appreciated.

**Comment by dshanske** [comment]
Resolved in v1.1.2
