### ISSUE TITLE
This Week Widget: Number Of Posts can not be changed

### ISSUE THREAD

**Issue by bekopharm** [dshanske/tempus-fugit#2]
The Week Widget can not adjust Number Of Posts:

![image](https://user-images.githubusercontent.com/5016428/111788229-202f4800-88c0-11eb-8884-0769c503814d.png)

Change is accepted with 200 Success server wise but it reverts back to 5 again.

Also: The appended link `/thisweek` is not a page and results in 404 but there is no option to opt out from that link.

**Comment by dshanske** [comment]
Save the Permalink page and it should regenerate the rewrite rules

**Comment by bekopharm** [comment]
> Permalink page

That worked :+1: 

So it's only Numbers Of Posts can not be saved :)

**Comment by dshanske** [comment]
Will investigate...it is also supposed to automatically refresh on update
