### ISSUE TITLE
On This Day page for previous days

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/tempus-fugit#6]
Is there a specific URL or datebased URL to navigate to previous days and see the list of entries on that specific day. Today is August 25th. I want to create a link on the archivepage to navigate on a per-day basis to previous days. So I would navigate to the On This Day page of August 24th. There is the link to August 23rd etc. Like the previous_post_link functionality. What would be the logical URL to use in these links?

**Comment by dshanske** [comment]
I have been thinking of adding a function to help with this...but /onthisday/08/24 would work if you needed the URL

**Comment by frankmeeuwsen** [comment]
I think that would work for now. Thanks!
